// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace POS.DbEntities
{
    public partial class CustomerAccountOrders
    {
        public CustomerAccountOrders()
        {
            CustomerAccountOrderItems = new HashSet<CustomerAccountOrderItems>();
        }



        public int CustomerAccountOrderId { get; set; }
        public int CustomerAccountId { get; set; }
        public string OrderNumber { get; set; }
        public DateTime OrderDate { get; set; }
        public decimal OrderTotal { get; set; }

        [NotMappedWrite]
        public DateTime CreatedOn { get; set; }

        [NotMappedWrite]
        public DateTime UpdatedOn { get; set; }

        [NotMappedWrite]
        public bool IsDeleted { get; set; }

        [NotMappedWrite]
        public virtual CustomerAccounts CustomerAccount { get; set; }

        [NotMappedWrite]
        public virtual ICollection<CustomerAccountOrderItems> CustomerAccountOrderItems { get; set; }
    }
}