// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace POS.DbEntities
{
    public partial class CustomerAccounts
    {
        public CustomerAccounts()
        {
            CustomerAccountOrders = new HashSet<CustomerAccountOrders>();
            CustomerAccountPayments = new HashSet<CustomerAccountPayments>();
        }

        public int CustomerAccountId { get; set; }
        public int CustomerId { get; set; }
        public string AccountNumber { get; set; }
        public string PhoneNumber { get; set; }
        public decimal Credit { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }

        public virtual Customers Customer { get; set; }
        public virtual ICollection<CustomerAccountOrders> CustomerAccountOrders { get; set; }
        public virtual ICollection<CustomerAccountPayments> CustomerAccountPayments { get; set; }
    }
}