// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace POS.DbEntities
{
    public partial class Products
    {
        public Products()
        {
            CustomerAccountOrderItems = new HashSet<CustomerAccountOrderItems>();
        }

        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string BarCode { get; set; }
        public int? ProductCatagoryId { get; set; }
        public int CompanyId { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }

        public virtual Companies Company { get; set; }
        public virtual ProductCatagories ProductCatagory { get; set; }
        public virtual ProductPrices ProductPrices { get; set; }
        public virtual ICollection<CustomerAccountOrderItems> CustomerAccountOrderItems { get; set; }
    }
}