// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace POS.DbEntities
{
    internal partial class VendorAccounts
    {
        public VendorAccounts()
        {
            VendorAccountOrders = new HashSet<VendorAccountOrders>();
            VendorAccountPayments = new HashSet<VendorAccountPayments>();
        }

        public int VendorAccountId { get; set; }
        public int VendorId { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public decimal CreditAmount { get; set; }
        public string Email { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }

        public virtual Vendors Vendor { get; set; }
        public virtual ICollection<VendorAccountOrders> VendorAccountOrders { get; set; }
        public virtual ICollection<VendorAccountPayments> VendorAccountPayments { get; set; }
    }
}