// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace POS.DbEntities
{
    internal partial class VendorAccountOrders
    {
        public VendorAccountOrders()
        {
            VendorAccountOrderItems = new HashSet<VendorAccountOrderItems>();
        }

        public int VendorAccountOrderId { get; set; }
        public int VendorAccountId { get; set; }
        public decimal OrderPrice { get; set; }
        public DateTime? OrderArrivedOn { get; set; }
        public DateTime OrderPlacedOn { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }

        public virtual Vendors VendorAccount { get; set; }
        public virtual ICollection<VendorAccountOrderItems> VendorAccountOrderItems { get; set; }
    }
}