// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace POS.DbEntities
{
    internal partial class VendorAccountOrderItems
    {
        public int VendorAccountOrderItemId { get; set; }
        public int ProductId { get; set; }
        public int VendorAccountOrderId { get; set; }
        public int ProductQuantity { get; set; }
        public decimal? BuyingPricePerUnit { get; set; }
        public decimal TotalBuyingPrice { get; set; }
        public bool IsSoldByPound { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }

        public virtual VendorAccountOrders VendorAccountOrder { get; set; }
    }
}