// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace POS.DbEntities
{
    public partial class VendorAccountPayments
    {
        [NotMappedWrite]
        public int VendorAccountPaymentId { get; set; }
        public int VendorAccountId { get; set; }
        public decimal PaymentAmount { get; set; }
        public decimal PaymentDate { get; set; }

        [NotMappedWrite]
        public DateTime CreatedOn { get; set; }

        [NotMappedWrite]
        public DateTime UpdatedOn { get; set; }

        [NotMappedWrite]
        public bool IsDeleted { get; set; }

        [NotMappedWrite]
        public virtual Vendors VendorAccount { get; set; }
    }
}